/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as HostRouteImport } from './routes/host'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as MIndexRouteImport } from './routes/m.index'
import { Route as HostSearchRouteImport } from './routes/host.search'
import { Route as HostRegisterRouteImport } from './routes/host.register'
import { Route as MIdIndexRouteImport } from './routes/m.$id.index'
import { Route as MIdVoteStandIdRouteImport } from './routes/m.$id.vote.$standId'

const HostRoute = HostRouteImport.update({
  id: '/host',
  path: '/host',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const MIndexRoute = MIndexRouteImport.update({
  id: '/m/',
  path: '/m/',
  getParentRoute: () => rootRouteImport,
} as any)
const HostSearchRoute = HostSearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => HostRoute,
} as any)
const HostRegisterRoute = HostRegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => HostRoute,
} as any)
const MIdIndexRoute = MIdIndexRouteImport.update({
  id: '/m/$id/',
  path: '/m/$id/',
  getParentRoute: () => rootRouteImport,
} as any)
const MIdVoteStandIdRoute = MIdVoteStandIdRouteImport.update({
  id: '/m/$id/vote/$standId',
  path: '/m/$id/vote/$standId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/host': typeof HostRouteWithChildren
  '/host/register': typeof HostRegisterRoute
  '/host/search': typeof HostSearchRoute
  '/m/': typeof MIndexRoute
  '/m/$id/': typeof MIdIndexRoute
  '/m/$id/vote/$standId': typeof MIdVoteStandIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/host': typeof HostRouteWithChildren
  '/host/register': typeof HostRegisterRoute
  '/host/search': typeof HostSearchRoute
  '/m': typeof MIndexRoute
  '/m/$id': typeof MIdIndexRoute
  '/m/$id/vote/$standId': typeof MIdVoteStandIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/host': typeof HostRouteWithChildren
  '/host/register': typeof HostRegisterRoute
  '/host/search': typeof HostSearchRoute
  '/m/': typeof MIndexRoute
  '/m/$id/': typeof MIdIndexRoute
  '/m/$id/vote/$standId': typeof MIdVoteStandIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/host'
    | '/host/register'
    | '/host/search'
    | '/m/'
    | '/m/$id/'
    | '/m/$id/vote/$standId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/host'
    | '/host/register'
    | '/host/search'
    | '/m'
    | '/m/$id'
    | '/m/$id/vote/$standId'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/host'
    | '/host/register'
    | '/host/search'
    | '/m/'
    | '/m/$id/'
    | '/m/$id/vote/$standId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  HostRoute: typeof HostRouteWithChildren
  MIndexRoute: typeof MIndexRoute
  MIdIndexRoute: typeof MIdIndexRoute
  MIdVoteStandIdRoute: typeof MIdVoteStandIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/host': {
      id: '/host'
      path: '/host'
      fullPath: '/host'
      preLoaderRoute: typeof HostRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/m/': {
      id: '/m/'
      path: '/m'
      fullPath: '/m/'
      preLoaderRoute: typeof MIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/host/search': {
      id: '/host/search'
      path: '/search'
      fullPath: '/host/search'
      preLoaderRoute: typeof HostSearchRouteImport
      parentRoute: typeof HostRoute
    }
    '/host/register': {
      id: '/host/register'
      path: '/register'
      fullPath: '/host/register'
      preLoaderRoute: typeof HostRegisterRouteImport
      parentRoute: typeof HostRoute
    }
    '/m/$id/': {
      id: '/m/$id/'
      path: '/m/$id'
      fullPath: '/m/$id/'
      preLoaderRoute: typeof MIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/m/$id/vote/$standId': {
      id: '/m/$id/vote/$standId'
      path: '/m/$id/vote/$standId'
      fullPath: '/m/$id/vote/$standId'
      preLoaderRoute: typeof MIdVoteStandIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface HostRouteChildren {
  HostRegisterRoute: typeof HostRegisterRoute
  HostSearchRoute: typeof HostSearchRoute
}

const HostRouteChildren: HostRouteChildren = {
  HostRegisterRoute: HostRegisterRoute,
  HostSearchRoute: HostSearchRoute,
}

const HostRouteWithChildren = HostRoute._addFileChildren(HostRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  HostRoute: HostRouteWithChildren,
  MIndexRoute: MIndexRoute,
  MIdIndexRoute: MIdIndexRoute,
  MIdVoteStandIdRoute: MIdVoteStandIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
