/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as HostRouteImport } from './routes/host'
import { Route as IndexRouteImport } from './routes/index'
import { Route as HostSearchRouteImport } from './routes/host.search'
import { Route as HostRegisterRouteImport } from './routes/host.register'

const HostRoute = HostRouteImport.update({
  id: '/host',
  path: '/host',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const HostSearchRoute = HostSearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => HostRoute,
} as any)
const HostRegisterRoute = HostRegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => HostRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/host': typeof HostRouteWithChildren
  '/host/register': typeof HostRegisterRoute
  '/host/search': typeof HostSearchRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/host': typeof HostRouteWithChildren
  '/host/register': typeof HostRegisterRoute
  '/host/search': typeof HostSearchRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/host': typeof HostRouteWithChildren
  '/host/register': typeof HostRegisterRoute
  '/host/search': typeof HostSearchRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/host' | '/host/register' | '/host/search'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/host' | '/host/register' | '/host/search'
  id: '__root__' | '/' | '/host' | '/host/register' | '/host/search'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  HostRoute: typeof HostRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/host': {
      id: '/host'
      path: '/host'
      fullPath: '/host'
      preLoaderRoute: typeof HostRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/host/search': {
      id: '/host/search'
      path: '/search'
      fullPath: '/host/search'
      preLoaderRoute: typeof HostSearchRouteImport
      parentRoute: typeof HostRoute
    }
    '/host/register': {
      id: '/host/register'
      path: '/register'
      fullPath: '/host/register'
      preLoaderRoute: typeof HostRegisterRouteImport
      parentRoute: typeof HostRoute
    }
  }
}

interface HostRouteChildren {
  HostRegisterRoute: typeof HostRegisterRoute
  HostSearchRoute: typeof HostSearchRoute
}

const HostRouteChildren: HostRouteChildren = {
  HostRegisterRoute: HostRegisterRoute,
  HostSearchRoute: HostSearchRoute,
}

const HostRouteWithChildren = HostRoute._addFileChildren(HostRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  HostRoute: HostRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
